### ISSUE TITLE
typos in week 1 blog

### ISSUE THREAD

**Issue by howtofly-lab** [ossd-s23/Charlie-XIAO-weekly#1]
Good blog. There are a few typos in the "Open Sourcing" section: 1st paragraph: "indiviual" -> individual, 2nd paragraph: "programmars" -> programmers, "struture" -> structure. In the Jupyter Notebook section, "Jupter" -> Jupyter :)

**Comment by Charlie-XIAO** [comment]
Sorry about the late reply. Thanks for noting these topos! I will fix them in my next update.
