### ISSUE TITLE
Incorrect team number in blog 4

### ISSUE THREAD

**Issue by jinlixiao** [ossd-s23/Charlie-XIAO-weekly#2]
Nice blog! I noticed that in your recent blog post on the project, you referred to the team of TabColor as Team 6, but instead it should be Team 8. 

The issue is at [here](https://github.com/ossd-s23/Charlie-XIAO-weekly/blob/cc2a453c5cf70198fb7deede7497d10603f1b578/_posts/2023-02-17-week04.md?plain=1#L26). And the full team list is [here](https://github.com/ossd-s23/wiki/wiki/Browser-extension-presentations).

**Comment by Charlie-XIAO** [comment]
Thanks for pointing out! I will fix that in my next push.
